/**
 * Configuration mapping patient IDs to their NFC card IDs and session tokens
 * This file is used as a store for session tokens after NFC authentication
 */
const users = {
  1: "2e0d0831-8cf6-4cec-9e0f-39d1ce64ba2c",
  2: "ee2ddcf4-1712-4840-a5ab-8708bc6810c8",
  3: "be135026-0295-448c-85de-39a64c83d067",
};

export default users;

const temp = {
  session: {
    id: 405,
    patient: {
      id: 3,
      email: "kaushikshahare2@gmail.com",
      user_type: "Patient",
      user_stage: 2,
      profile: {
        patient_id: 3,
        name: "Kaushik Shahare",
        gender: "Male",
        date_of_birth: "1995-07-12",
        age: 29,
        email: "kaushikshahare2@gmail.com",
        phone_number: "9359139756",
        location: "Mumbai, Maharashtra",
        blood_group: "B+",
        height_cm: 172,
        weight_kg: 68,
        marital_status: "Single",
        allergies: ["Penicillin"],
        chronic_conditions: ["Asthma"],
        current_medications: ["Inhaler (Salbutamol)"],
        last_visit: "2025-05-30",
        vaccination_status: {
          covid19: "Completed",
          tetanus: "Completed",
          hepatitis_b: "Completed",
        },
        user_type: "Patient",
        address: {
          id: 2,
          street: "B-201, Sagar Heights",
          area: "Andheri East",
          city: "Mumbai",
          state: "Maharashtra",
          pincode: "400069",
          country: "India",
          is_primary: true,
        },
        emergency_contact: {
          id: 2,
          name: "Rajesh Mishra",
          relation: "Father",
          phone_number: "9823123456",
        },
        insurance: {
          id: 2,
          provider: "Star Health Insurance",
          policy_number: "STH12345678",
          valid_till: "2026-03-31",
        },
        primary_physician: {
          name: "Dr. Unknown",
          department: "Pulmonology",
          hospital: "Apollo Hospitals, Mumbai",
        },
      },
    },
    accessed_by: {
      id: 2,
      email: "kaushikshahare1@gmail.com",
      user_type: "Doctor",
      user_stage: 2,
      profile: {
        patient_id: 2,
        name: "Harsh Dasai",
        gender: "Male",
        date_of_birth: "1995-07-12",
        age: 29,
        email: "kaushikshahare1@gmail.com",
        phone_number: "9359139756",
        location: "Mumbai, Maharashtra",
        blood_group: "B+",
        height_cm: 172,
        weight_kg: 68,
        marital_status: "Single",
        allergies: ["Penicillin"],
        chronic_conditions: ["Asthma"],
        current_medications: ["Inhaler (Salbutamol)"],
        last_visit: "2025-05-30",
        vaccination_status: {
          covid19: "Completed",
          tetanus: "Completed",
          hepatitis_b: "Completed",
        },
        user_type: "Doctor",
        address: {
          id: 1,
          street: "B-201, Sagar Heights",
          area: "Andheri East",
          city: "Mumbai",
          state: "Maharashtra",
          pincode: "400069",
          country: "India",
          is_primary: true,
        },
        emergency_contact: {
          id: 1,
          name: "Rajesh Mishra",
          relation: "Father",
          phone_number: "9823123456",
        },
        insurance: {
          id: 1,
          provider: "Star Health Insurance",
          policy_number: "STH12345678",
          valid_till: "2026-03-31",
        },
        primary_physician: {
          name: "Dr. Unknown",
          department: "Pulmonology",
          hospital: "Apollo Hospitals, Mumbai",
        },
      },
    },
    session_type: "doctor",
    session_token: "WgGYnh-ubBnUY8wLx4NuA9_esRRVDSHqMgr1pCF-O9I",
    started_at: "2025-06-27T08:41:01.716014Z",
    expires_at: "2025-06-27T12:41:01.715869Z",
    is_active: true,
    valid: true,
    visit: null,
  },
  access_type: "doctor",
  documents_url:
    "/api/ehr/nfc/session/WgGYnh-ubBnUY8wLx4NuA9_esRRVDSHqMgr1pCF-O9I/documents/",
  expires_at: "2025-06-27T12:41:01.715869Z",
  access_level: "Full access",
  visit: null,
  patient: {
    name: "Kaushik Shahare",
    date_of_birth: "1995-07-12",
    phone_number: "9359139756",
  },
};
